//! Commands run only after an explicit user action, in the selected worktree.
//! Streaming run logs and persistent line-oriented shells share the bottom panel.

use eframe::egui::{self, RichText};
use pie_crust_core::{PythonProjectLayout, discover_python_environment};
use serde::{Deserialize, Serialize};
use std::collections::VecDeque;
use std::fs;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::mpsc::{self, Receiver, Sender, SyncSender};
use std::thread::{self, JoinHandle};
use std::time::{Duration, Instant};

#[path = "terminal.rs"]
mod terminal;

const OUTPUT_LIMIT: usize = 1024 * 1024;
const HISTORY_LIMIT: usize = 24;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub(super) enum BottomView {
    Terminal,
    Tests,
    #[default]
    Run,
}

/// A click captures its target before the desktop saves and synchronizes documents.
#[derive(Clone, Debug)]
pub(super) struct RunRequest {
    pub name: String,
    pub command: String,
    pub view: BottomView,
    pub worktree_id: String,
    pub root: PathBuf,
    pub terminal_id: Option<u64>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
struct RunConfig {
    name: String,
    command: String,
    #[serde(default)]
    view: BottomView,
    /// Relative to the selected worktree. Older/custom configurations keep its root.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    working_directory: Option<PathBuf>,
    /// Refresh only commands that still match the value generated by discovery.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    generated_command: Option<String>,
}

#[derive(Serialize, Deserialize)]
struct ConfigFile {
    version: u32,
    configurations: Vec<RunConfig>,
}

pub(super) struct RunPanel {
    config_path: PathBuf,
    worktree_id: String,
    worktree_root: PathBuf,
    source_roots: Vec<PathBuf>,
    primary_source_root: PathBuf,
    configurations: Vec<RunConfig>,
    selected_config: usize,
    popup_open: bool,
    focus_command: bool,
    edit_name: String,
    edit_command: String,
    edit_view: BottomView,
    terminal_command: String,
    sessions: Vec<RunSession>,
    selected_session: Option<u64>,
    next_session: u64,
    error: Option<String>,
    requested_view: Option<BottomView>,
    run_requests: VecDeque<RunRequest>,
    terminals: terminal::Terminals,
}

impl RunPanel {
    pub(super) fn active_terminal_selection(&self, ctx: &egui::Context) -> Option<String> {
        self.terminals.active_selection(ctx)
    }

    pub(super) fn new(project_root: PathBuf) -> Self {
        let config_path = project_root.join(".pie_crust/run-configs.json");
        let (source_roots, primary_source_root) = discover_source_roots(&project_root);
        let (mut configurations, error) = match read_configs(&config_path) {
            Ok(Some(configurations)) => (configurations, None),
            Ok(None) => (default_configs(&project_root, &primary_source_root), None),
            Err(error) => (
                default_configs(&project_root, &primary_source_root),
                Some(format!("Configurations de lancement : {error}")),
            ),
        };
        refresh_generated_configs(
            &mut configurations,
            &project_root,
            &primary_source_root,
            &source_roots,
        );
        let mut panel = Self {
            config_path,
            worktree_id: String::new(),
            worktree_root: project_root,
            source_roots,
            primary_source_root,
            configurations,
            selected_config: 0,
            popup_open: false,
            focus_command: false,
            edit_name: String::new(),
            edit_command: String::new(),
            edit_view: BottomView::Run,
            terminal_command: String::new(),
            sessions: Vec::new(),
            selected_session: None,
            next_session: 1,
            error,
            requested_view: None,
            run_requests: VecDeque::new(),
            terminals: terminal::Terminals::default(),
        };
        panel.load_selected();
        panel
    }

    pub(super) fn set_worktree(&mut self, id: impl Into<String>, root: PathBuf) {
        self.worktree_id = id.into();
        if self.worktree_root != root {
            (self.source_roots, self.primary_source_root) = discover_source_roots(&root);
            self.worktree_root = root;
            self.refresh_configurations();
        }
    }

    /// Capture configuration only; discovery runs when the returned job is called.
    pub(super) fn prepare_worktree(
        &self,
        id: String,
        root: PathBuf,
    ) -> impl FnOnce() -> Self + Send + 'static + use<> {
        let mut prepared = Self {
            config_path: self.config_path.clone(),
            worktree_id: self.worktree_id.clone(),
            worktree_root: self.worktree_root.clone(),
            source_roots: self.source_roots.clone(),
            primary_source_root: self.primary_source_root.clone(),
            configurations: self.configurations.clone(),
            selected_config: self.selected_config,
            popup_open: false,
            focus_command: false,
            edit_name: self.edit_name.clone(),
            edit_command: self.edit_command.clone(),
            edit_view: self.edit_view,
            terminal_command: self.terminal_command.clone(),
            sessions: Vec::new(),
            selected_session: None,
            next_session: 1,
            error: self.error.clone(),
            requested_view: None,
            run_requests: VecDeque::new(),
            terminals: terminal::Terminals::default(),
        };
        move || {
            prepared.set_worktree(id, root);
            prepared
        }
    }

    /// Adopt prepared project data without touching running processes or doing I/O.
    pub(super) fn adopt_project(&mut self, prepared: Self) {
        self.config_path = prepared.config_path;
        self.worktree_id = prepared.worktree_id;
        self.worktree_root = prepared.worktree_root;
        self.source_roots = prepared.source_roots;
        self.primary_source_root = prepared.primary_source_root;
        self.configurations = prepared.configurations;
        self.selected_config = prepared.selected_config;
        self.edit_name = prepared.edit_name;
        self.edit_command = prepared.edit_command;
        self.edit_view = prepared.edit_view;
        self.terminal_command = prepared.terminal_command;
        self.error = prepared.error;
    }

    pub(super) fn open_run_popup(&mut self) {
        self.popup_open = true;
        self.focus_command = true;
    }

    pub(super) fn is_running(&self) -> bool {
        self.terminals.is_running() || self.sessions.iter().any(|session| session.is_running())
    }

    pub(super) fn requested_view(&mut self) -> Option<BottomView> {
        if std::mem::take(&mut self.terminals.requested_view) {
            return Some(BottomView::Terminal);
        }
        self.requested_view.take()
    }

    pub(super) fn open_terminal_drawer(&mut self) {
        self.terminals.open_drawer();
    }

    pub(super) fn take_close_drawer(&mut self) -> bool {
        self.terminals.take_close_drawer()
    }

    pub(super) fn poll(&mut self) -> bool {
        let mut changed = self.terminals.poll();
        for session in &mut self.sessions {
            changed |= session.poll();
        }
        changed
    }

    pub(super) fn run_selected(&mut self) {
        if let Some(configuration) = self.configurations.get(self.selected_config).cloned() {
            self.run_command_in_directory(
                &configuration.name,
                &configuration.command,
                configuration.view,
                configuration.working_directory.as_deref(),
            );
        } else {
            self.open_run_popup();
        }
    }

    pub(super) fn run_command(&mut self, name: &str, command: &str, view: BottomView) {
        self.run_command_in_directory(name, command, view, None);
    }

    fn run_command_in_directory(
        &mut self,
        name: &str,
        command: &str,
        view: BottomView,
        directory: Option<&Path>,
    ) {
        let command = command.trim();
        if command.is_empty() {
            self.error = Some("Saisissez une commande à exécuter.".into());
            return;
        }
        if !self.worktree_root.is_dir() {
            self.error = Some("Le dossier du worktree n’est plus disponible.".into());
            return;
        }
        let command = match command_in_directory(&self.worktree_root, directory, command) {
            Ok(command) => command,
            Err(error) => {
                self.error = Some(error);
                return;
            }
        };
        if self
            .sessions
            .iter()
            .filter(|session| session.is_running())
            .count()
            + self.run_requests.len()
            >= 8
        {
            self.error =
                Some("Arrêtez une exécution avant d’en lancer une autre (8 maximum).".into());
            return;
        }
        self.run_requests.push_back(RunRequest {
            name: name.to_owned(),
            command,
            view,
            worktree_id: self.worktree_id.clone(),
            root: self.worktree_root.clone(),
            terminal_id: None,
        });
        self.requested_view = Some(view);
        self.error = None;
    }

    pub(super) fn take_run_request(&mut self) -> Option<RunRequest> {
        self.run_requests.pop_front()
    }

    pub(super) fn set_launch_error(&mut self, message: impl Into<String>) {
        self.error = Some(message.into());
    }

    /// Called by the desktop only after the requested worktree's buffers were saved.
    pub(super) fn start_request(&mut self, request: RunRequest) -> bool {
        if request.command.trim().is_empty() {
            self.set_launch_error("Saisissez une commande à exécuter.");
            return false;
        }
        if !request.root.is_dir() {
            self.set_launch_error("Le dossier du worktree n’est plus disponible.");
            return false;
        }
        if request.view == BottomView::Terminal {
            match self.terminals.start_request(request) {
                Ok(()) => {
                    self.error = None;
                    return true;
                }
                Err(error) => {
                    self.set_launch_error(error);
                    return false;
                }
            }
        }
        if self
            .sessions
            .iter()
            .filter(|session| session.is_running())
            .count()
            >= 8
        {
            self.set_launch_error("Arrêtez une exécution avant d’en lancer une autre (8 maximum).");
            return false;
        }
        while self.sessions.len() >= HISTORY_LIMIT {
            if let Some(index) = self
                .sessions
                .iter()
                .position(|session| !session.is_running())
            {
                self.sessions.remove(index);
            } else {
                break;
            }
        }
        let id = self.next_session;
        self.next_session += 1;
        self.sessions.push(RunSession::start(
            id,
            request.name,
            request.command,
            request.view,
            request.worktree_id,
            request.root,
        ));
        self.selected_session = Some(id);
        self.requested_view = Some(request.view);
        self.error = None;
        true
    }

    /// `args` is an explicitly selected command fragment, not a filename to interpolate.
    pub(super) fn run_python_command_in_source_root(
        &mut self,
        name: &str,
        args: &str,
        view: BottomView,
        source_root: &Path,
    ) -> bool {
        let command = format!(
            "{} {args}",
            python_interpreter_in_source_root(&self.worktree_root, source_root)
        );
        let pending = self.run_requests.len();
        self.run_command_in_directory(name, &command, view, Some(source_root));
        self.run_requests.len() > pending
    }

    pub(super) fn completed_output_for(
        &self,
        worktree_id: &str,
        name: &str,
    ) -> Option<(u64, bool, &str)> {
        self.sessions
            .iter()
            .rev()
            .find(|session| {
                session.worktree_id == worktree_id && session.name == name && !session.is_running()
            })
            .map(|session| {
                (
                    session.id,
                    session.result == Some((Some(0), false)),
                    session.output.as_str(),
                )
            })
    }

    pub(super) fn command_is_pending_or_running(&self, worktree_id: &str, name: &str) -> bool {
        self.run_requests
            .iter()
            .any(|request| request.worktree_id == worktree_id && request.name == name)
            || self.sessions.iter().any(|session| {
                session.worktree_id == worktree_id && session.name == name && session.is_running()
            })
    }

    pub(super) fn show_run_controls(&mut self, ui: &mut egui::Ui) {
        let name = self
            .configurations
            .get(self.selected_config)
            .map_or("Commande…", |configuration| configuration.name.as_str());
        if ui
            .button(format!("{name}  ▾"))
            .on_hover_text("Configurations de lancement · Ctrl+R")
            .clicked()
        {
            self.open_run_popup();
        }
        if ui
            .button(RichText::new("▶").color(egui::Color32::from_rgb(118, 194, 137)))
            .on_hover_text("Exécuter la configuration sélectionnée")
            .clicked()
        {
            self.run_selected();
        }
        if self.is_running()
            && ui
                .button("■")
                .on_hover_text("Arrêter les commandes en cours")
                .clicked()
        {
            for session in &mut self.sessions {
                session.stop();
            }
            self.terminals.stop_all();
        }
    }

    pub(super) fn show_drawer(&mut self, ui: &mut egui::Ui, view: BottomView) {
        if view == BottomView::Terminal {
            self.terminals
                .show_drawer(ui, &self.worktree_id, &self.worktree_root);
            self.show_error(ui);
            return;
        }
        ui.label(match view {
            BottomView::Terminal => "Console de commandes",
            BottomView::Tests => "Commandes de test",
            BottomView::Run => "Configurations de lancement",
        });
        ui.add_space(6.0);
        if view == BottomView::Terminal {
            ui.label("Exécutez vos commandes dans le worktree actif. Chaque commande démarre un nouveau shell.");
            if ui.button("Ouvrir la console").clicked() {
                self.requested_view = Some(view);
            }
        } else {
            let mut run = None;
            let mut selected = None;
            for (index, configuration) in self.configurations.iter().enumerate() {
                if view == BottomView::Tests && configuration.view != BottomView::Tests {
                    continue;
                }
                ui.horizontal(|ui| {
                    if ui
                        .selectable_label(self.selected_config == index, &configuration.name)
                        .on_hover_text(&configuration.command)
                        .clicked()
                    {
                        selected = Some(index);
                    }
                    if ui.small_button("▶").on_hover_text("Exécuter").clicked() {
                        run = Some(index);
                    }
                });
            }
            if let Some(index) = selected {
                self.selected_config = index;
                self.load_selected();
            }
            if let Some(index) = run {
                self.selected_config = index;
                self.load_selected();
                self.run_selected();
            }
            if ui.button("Configurer…  Ctrl+R").clicked() {
                self.load_selected();
                self.open_run_popup();
            }
        }
        ui.add_space(12.0);
        ui.label(RichText::new("EXÉCUTIONS").small().weak());
        let mut selected = None;
        for session in self
            .sessions
            .iter()
            .rev()
            .filter(|session| session.view == view)
        {
            let label = format!("{}  {}", session.status_symbol(), session.name);
            if ui
                .selectable_label(self.selected_session == Some(session.id), label)
                .on_hover_text(format!("{}\n{}", session.root.display(), session.command))
                .clicked()
            {
                selected = Some(session.id);
            }
        }
        if let Some(id) = selected {
            self.selected_session = Some(id);
            self.requested_view = Some(view);
        }
        self.show_error(ui);
    }

    pub(super) fn show_bottom_content(&mut self, ui: &mut egui::Ui, view: BottomView) {
        if view == BottomView::Terminal {
            if let Some(request) =
                self.terminals
                    .show_bottom(ui, &self.worktree_id, &self.worktree_root)
            {
                self.run_requests.push_back(request);
            }
            self.show_error(ui);
            return;
        }
        ui.horizontal(|ui| {
            if view == BottomView::Terminal {
                let response = ui.add(
                    egui::TextEdit::singleline(&mut self.terminal_command)
                        .id_salt("terminal_command")
                        .hint_text("Commande dans le worktree actif…")
                        .desired_width((ui.available_width() - 110.0).max(100.0)),
                );
                let enter =
                    response.lost_focus() && ui.input(|input| input.key_pressed(egui::Key::Enter));
                if ui.button("Exécuter").clicked() || enter {
                    let command = self.terminal_command.trim().to_owned();
                    self.run_command(&command, &command, BottomView::Terminal);
                    if !command.is_empty() {
                        self.terminal_command.clear();
                    }
                    response.request_focus();
                }
            } else if ui.button("Configurations…  Ctrl+R").clicked() {
                self.open_run_popup();
            }
        });
        ui.horizontal_wrapped(|ui| {
            for session in self.sessions.iter().filter(|session| session.view == view) {
                let label = format!("{} {}", session.status_symbol(), session.name);
                if ui
                    .selectable_label(self.selected_session == Some(session.id), label)
                    .clicked()
                {
                    self.selected_session = Some(session.id);
                }
            }
        });
        self.show_error(ui);
        let index = self
            .selected_session
            .and_then(|id| {
                self.sessions
                    .iter()
                    .position(|session| session.id == id && session.view == view)
            })
            .or_else(|| {
                self.sessions
                    .iter()
                    .rposition(|session| session.view == view)
            });
        let Some(index) = index else {
            ui.add_space(8.0);
            ui.label(match view {
                BottomView::Terminal => "Les sorties apparaîtront ici. Cette console accepte des commandes et des lignes d’entrée ; les applications plein écran nécessitent un terminal externe.",
                BottomView::Tests => "Lancez une commande de test depuis le volet gauche ou Ctrl+R. Son résultat et son code de sortie apparaîtront ici.",
                BottomView::Run => "Ctrl+R pour choisir un script ou saisir une nouvelle commande.",
            });
            ui.label(
                RichText::new(self.worktree_root.display().to_string())
                    .small()
                    .weak(),
            );
            return;
        };
        let session = &mut self.sessions[index];
        ui.horizontal(|ui| {
            ui.label(RichText::new(session.status_text()).strong());
            ui.label(
                RichText::new(session.root.display().to_string())
                    .small()
                    .weak(),
            )
            .on_hover_text(format!(
                "Worktree : {}\n{}",
                session.worktree_id, session.command
            ));
            if session.is_running() && ui.small_button("Arrêter").clicked() {
                session.stop();
            }
            if ui.small_button("Copier").clicked() {
                ui.ctx().copy_text(session.output.clone());
            }
            if ui.small_button("Effacer").clicked() {
                session.output.clear();
                session.truncated = false;
            }
        });
        if session.is_running() {
            ui.horizontal(|ui| {
                let response = ui.add(
                    egui::TextEdit::singleline(&mut session.stdin)
                        .id_salt(("run_stdin", session.id))
                        .hint_text("Entrée standard…")
                        .desired_width((ui.available_width() - 180.0).max(100.0)),
                );
                let enter =
                    response.lost_focus() && ui.input(|input| input.key_pressed(egui::Key::Enter));
                if ui.button("Envoyer").clicked() || enter {
                    let line = std::mem::take(&mut session.stdin);
                    let _ = session.control.send(Control::Input(format!("{line}\n")));
                    response.request_focus();
                }
                if ui
                    .button("Fin d’entrée")
                    .on_hover_text("Fermer stdin (EOF)")
                    .clicked()
                {
                    let _ = session.control.send(Control::CloseInput);
                }
            });
        }
        if session.truncated {
            ui.label(
                RichText::new("Début du journal retiré : affichage limité au dernier Mio.")
                    .small()
                    .weak(),
            );
        }
        ui.separator();
        egui::ScrollArea::both()
            .id_salt(("run_output", session.id))
            .auto_shrink([false, false])
            .stick_to_bottom(true)
            .show(ui, |ui| {
                ui.add(
                    egui::Label::new(RichText::new(&session.output).monospace()).selectable(true),
                );
            });
    }

    pub(super) fn show_run_popup(&mut self, ctx: &egui::Context) {
        if !self.popup_open {
            return;
        }
        let mut open = true;
        let mut close = false;
        egui::Window::new("Exécuter une commande")
            .id(egui::Id::new("run_configuration_popup"))
            .open(&mut open)
            .collapsible(false)
            .default_width(680.0)
            .show(ctx, |ui| {
                ui.label(
                    RichText::new(self.worktree_root.display().to_string())
                        .small()
                        .weak(),
                );
                let mut selected = None;
                egui::ComboBox::from_id_salt("run_configuration_picker")
                    .width(430.0)
                    .selected_text(
                        self.configurations
                            .get(self.selected_config)
                            .map_or("Nouvelle commande", |configuration| {
                                configuration.name.as_str()
                            }),
                    )
                    .show_ui(ui, |ui| {
                        for (index, configuration) in self.configurations.iter().enumerate() {
                            if ui
                                .selectable_label(
                                    index == self.selected_config,
                                    &configuration.name,
                                )
                                .clicked()
                            {
                                selected = Some(index);
                            }
                        }
                    });
                if let Some(index) = selected {
                    self.selected_config = index;
                    self.load_selected();
                }
                if ui.button("Actualiser les scripts").on_hover_text("Détecter les dossiers de sources et leurs scripts Python, sans exécuter de code").clicked() {
                    self.refresh_scripts();
                }
                ui.add_space(8.0);
                ui.label("Nom");
                ui.add(
                    egui::TextEdit::singleline(&mut self.edit_name).desired_width(f32::INFINITY),
                );
                ui.label("Commande");
                let command_response = ui.add(
                    egui::TextEdit::singleline(&mut self.edit_command)
                        .id_salt("run_command_edit")
                        .font(egui::TextStyle::Monospace)
                        .hint_text("python -m mon_module --option")
                        .desired_width(f32::INFINITY),
                );
                if self.focus_command {
                    command_response.request_focus();
                    self.focus_command = false;
                }
                let directory = self.configurations.get(self.selected_config)
                    .and_then(|configuration| configuration.working_directory.as_deref())
                    .unwrap_or_else(|| Path::new("."));
                ui.label(
                    RichText::new(format!(
                        "Shell : {} · dossier de travail : {}",
                        if cfg!(windows) { "PowerShell" } else { "/bin/sh" },
                        self.worktree_root.join(directory).display(),
                    ))
                    .small()
                    .weak(),
                );
                ui.horizontal(|ui| {
                    ui.label("Afficher dans");
                    ui.selectable_value(&mut self.edit_view, BottomView::Run, "Exécution");
                    ui.selectable_value(&mut self.edit_view, BottomView::Tests, "Tests");
                });
                ui.add_space(8.0);
                ui.horizontal(|ui| {
                    if ui.button("Nouvelle").clicked() {
                        self.edit_name.clear();
                        self.edit_command.clear();
                        self.selected_config = self.configurations.len();
                        self.focus_command = true;
                    }
                    if ui.button("Enregistrer").clicked() {
                        self.save_edited();
                    }
                    if ui
                        .add_enabled(
                            self.selected_config < self.configurations.len(),
                            egui::Button::new("Supprimer"),
                        )
                        .clicked()
                    {
                        let mut updated = self.configurations.clone();
                        updated.remove(self.selected_config);
                        if self.persist(&updated) {
                            self.configurations = updated;
                            self.selected_config = 0;
                            self.load_selected();
                        }
                    }
                    let enter = command_response.lost_focus()
                        && ui.input(|input| input.key_pressed(egui::Key::Enter));
                    if ui.button("▶ Exécuter").clicked() || enter {
                        let name = if self.edit_name.trim().is_empty() {
                            self.edit_command.clone()
                        } else {
                            self.edit_name.clone()
                        };
                        let command = self.edit_command.clone();
                        let directory = self.configurations.get(self.selected_config)
                            .and_then(|configuration| configuration.working_directory.clone());
                        self.run_command_in_directory(&name, &command, self.edit_view, directory.as_deref());
                        close = !command.trim().is_empty() && self.error.is_none();
                    }
                });
                self.show_error(ui);
            });
        self.popup_open = open && !close;
    }

    fn load_selected(&mut self) {
        if let Some(configuration) = self.configurations.get(self.selected_config) {
            self.edit_name.clone_from(&configuration.name);
            self.edit_command.clone_from(&configuration.command);
            self.edit_view = configuration.view;
        } else {
            self.edit_name.clear();
            self.edit_command.clear();
            self.edit_view = BottomView::Run;
        }
    }

    fn refresh_scripts(&mut self) {
        (self.source_roots, self.primary_source_root) = discover_source_roots(&self.worktree_root);
        self.refresh_configurations();
    }

    fn refresh_configurations(&mut self) {
        let unedited_selection =
            self.configurations
                .get(self.selected_config)
                .is_some_and(|configuration| {
                    configuration.name == self.edit_name
                        && configuration.command == self.edit_command
                        && configuration.view == self.edit_view
                });
        let selected_name = self
            .configurations
            .get(self.selected_config)
            .map(|configuration| configuration.name.clone());
        refresh_generated_configs(
            &mut self.configurations,
            &self.worktree_root,
            &self.primary_source_root,
            &self.source_roots,
        );
        self.selected_config = if let Some(name) = selected_name {
            self.configurations
                .iter()
                .position(|configuration| configuration.name == name)
                .unwrap_or(0)
        } else {
            self.configurations.len()
        };
        if unedited_selection {
            self.load_selected();
        }
    }

    fn save_edited(&mut self) {
        if self.edit_name.trim().is_empty() || self.edit_command.trim().is_empty() {
            self.error = Some("Indiquez un nom et une commande pour cette configuration.".into());
            return;
        }
        let configuration = RunConfig {
            name: self.edit_name.trim().into(),
            command: self.edit_command.trim().into(),
            view: self.edit_view,
            working_directory: self
                .configurations
                .get(self.selected_config)
                .and_then(|configuration| configuration.working_directory.clone()),
            generated_command: self
                .configurations
                .get(self.selected_config)
                .filter(|configuration| {
                    configuration.name == self.edit_name.trim()
                        && configuration.command == self.edit_command.trim()
                        && configuration.view == self.edit_view
                })
                .and_then(|configuration| configuration.generated_command.clone()),
        };
        let mut updated = self.configurations.clone();
        let index = if self.selected_config < updated.len() {
            updated[self.selected_config] = configuration;
            self.selected_config
        } else {
            updated.push(configuration);
            updated.len() - 1
        };
        if self.persist(&updated) {
            self.configurations = updated;
            self.selected_config = index;
        }
    }

    fn persist(&mut self, configurations: &[RunConfig]) -> bool {
        match write_configs(&self.config_path, configurations) {
            Ok(()) => {
                self.error = None;
                true
            }
            Err(error) => {
                self.error = Some(format!("Enregistrement impossible : {error}"));
                false
            }
        }
    }

    fn show_error(&mut self, ui: &mut egui::Ui) {
        if let Some(error) = &self.error {
            ui.colored_label(ui.visuals().error_fg_color, error);
        }
    }
}

fn discover_source_roots(root: &Path) -> (Vec<PathBuf>, PathBuf) {
    match PythonProjectLayout::discover(root) {
        Ok(layout) => (layout.source_roots, layout.primary_source_root),
        Err(_) => (vec![PathBuf::from(".")], PathBuf::from(".")),
    }
}

fn command_in_directory(
    root: &Path,
    directory: Option<&Path>,
    command: &str,
) -> Result<String, String> {
    let Some(directory) = directory else {
        return Ok(command.to_owned());
    };
    if directory.components().any(|component| {
        !matches!(
            component,
            std::path::Component::Normal(_) | std::path::Component::CurDir
        )
    }) {
        return Err("Le dossier de lancement doit être relatif au worktree actif.".into());
    }
    if directory
        .components()
        .all(|component| component == std::path::Component::CurDir)
    {
        return Ok(command.to_owned());
    }
    let target = root.join(directory);
    if !target.is_dir()
        || !root.canonicalize().is_ok_and(|root| {
            target
                .canonicalize()
                .is_ok_and(|target| target.starts_with(root))
        })
    {
        return Err("Le dossier de sources n’est plus disponible dans le worktree actif.".into());
    }
    // Keep RunRequest.root at the worktree so save/sync validation retains its identity.
    let directory = quote_shell_argument(
        &format!("./{}", directory.to_string_lossy().replace('\\', "/")),
        cfg!(windows),
    );
    Ok(if cfg!(windows) {
        format!("Set-Location -LiteralPath {directory} -ErrorAction Stop; {command}")
    } else {
        format!("cd {directory} && {command}")
    })
}

fn python_interpreter_in_source_root(root: &Path, source_root: &Path) -> String {
    let Some(environment) = discover_python_environment(root, source_root) else {
        return if cfg!(windows) { "python" } else { "python3" }.into();
    };
    let source_components: Vec<_> = source_root
        .components()
        .filter(|component| *component != std::path::Component::CurDir)
        .collect();
    let interpreter_components: Vec<_> = environment
        .interpreter
        .components()
        .filter(|component| *component != std::path::Component::CurDir)
        .collect();
    let shared = source_components
        .iter()
        .zip(&interpreter_components)
        .take_while(|(source, interpreter)| source == interpreter)
        .count();
    let mut relative = PathBuf::from(".");
    for _ in shared..source_components.len() {
        relative.push("..");
    }
    for component in &interpreter_components[shared..] {
        relative.push(component.as_os_str());
    }
    let interpreter = quote_shell_argument(
        &relative.to_string_lossy().replace('\\', "/"),
        cfg!(windows),
    );
    if cfg!(windows) {
        format!("& {interpreter}")
    } else {
        interpreter
    }
}

fn default_configs(root: &Path, source_root: &Path) -> Vec<RunConfig> {
    let interpreter = python_interpreter_in_source_root(root, source_root);
    let mut configurations = vec![
        RunConfig {
            name: "Tests · unittest".into(),
            command: format!("{interpreter} -m unittest discover -s tests -v"),
            generated_command: Some(format!("{interpreter} -m unittest discover -s tests -v")),
            view: BottomView::Tests,
            working_directory: Some(source_root.to_owned()),
        },
        RunConfig {
            name: "Tests · pytest".into(),
            command: format!("{interpreter} -m pytest"),
            generated_command: Some(format!("{interpreter} -m pytest")),
            view: BottomView::Tests,
            working_directory: Some(source_root.to_owned()),
        },
    ];
    if root.join(source_root).join("manage.py").is_file() {
        configurations.push(RunConfig {
            name: "Django · serveur".into(),
            command: format!("{interpreter} manage.py runserver"),
            generated_command: Some(format!("{interpreter} manage.py runserver")),
            view: BottomView::Run,
            working_directory: Some(source_root.to_owned()),
        });
        configurations.push(RunConfig {
            name: "Django · tests".into(),
            command: format!("{interpreter} manage.py test"),
            generated_command: Some(format!("{interpreter} manage.py test")),
            view: BottomView::Tests,
            working_directory: Some(source_root.to_owned()),
        });
    }
    configurations
}

fn refresh_generated_configs(
    configurations: &mut Vec<RunConfig>,
    root: &Path,
    primary_source_root: &Path,
    source_roots: &[PathBuf],
) {
    let mut discovered = default_configs(root, primary_source_root);
    let default_count = discovered.len();
    append_discovered_scripts(&mut discovered, root, source_roots);
    configurations.retain_mut(|configuration| {
        if configuration.generated_command.as_ref() != Some(&configuration.command) {
            configuration.generated_command = None;
            return true;
        }
        if let Some(updated) = discovered
            .iter()
            .find(|updated| updated.name == configuration.name)
        {
            *configuration = updated.clone();
            true
        } else {
            false
        }
    });
    // Saved deletions of default launch configurations remain respected.
    for configuration in discovered.into_iter().skip(default_count) {
        if !configurations.iter().any(|existing| {
            existing.name == configuration.name
                || (existing.command == configuration.command
                    && existing.working_directory == configuration.working_directory)
        }) {
            configurations.push(configuration);
        }
    }
}

fn append_discovered_scripts(
    configurations: &mut Vec<RunConfig>,
    root: &Path,
    source_roots: &[PathBuf],
) {
    for configuration in source_roots
        .iter()
        .flat_map(|source_root| discover_scripts(root, source_root))
        .take(64)
    {
        if !configurations.iter().any(|existing| {
            existing.name == configuration.name
                || (existing.command == configuration.command
                    && existing.working_directory == configuration.working_directory)
        }) {
            configurations.push(configuration);
        }
    }
}

fn discover_scripts(root: &Path, source_root: &Path) -> Vec<RunConfig> {
    let Ok(canonical_root) = root.canonicalize() else {
        return Vec::new();
    };
    let source_directory = root.join(source_root);
    let mut scripts = Vec::new();
    for directory in [source_directory.clone(), source_directory.join("scripts")] {
        if !directory
            .canonicalize()
            .is_ok_and(|path| path.starts_with(&canonical_root))
        {
            continue;
        }
        let Ok(entries) = fs::read_dir(&directory) else {
            continue;
        };
        // Bound discovery even in a directory containing thousands of unrelated files.
        for entry in entries.take(4096).flatten() {
            if !entry.file_type().is_ok_and(|kind| kind.is_file()) {
                continue;
            }
            let path = entry.path();
            let Some(name) = path.file_name().and_then(|value| value.to_str()) else {
                continue;
            };
            if path.extension().is_none_or(|extension| extension != "py")
                || name == "manage.py"
                || name == "__init__.py"
                || name.starts_with("test_")
                || name.ends_with("_test.py")
                || name == "test.py"
                || name == "tests.py"
            {
                continue;
            }
            let Ok(relative) = path.strip_prefix(&source_directory) else {
                continue;
            };
            scripts.push(relative.to_string_lossy().replace('\\', "/"));
        }
    }
    scripts.sort();
    scripts.dedup();
    scripts.truncate(64);
    let interpreter = python_interpreter_in_source_root(root, source_root);
    scripts
        .into_iter()
        .map(|path| RunConfig {
            name: format!(
                "Python · {}",
                if source_root == Path::new(".") {
                    path.clone()
                } else {
                    source_root.join(&path).to_string_lossy().replace('\\', "/")
                }
            ),
            command: format!(
                "{interpreter} {}",
                quote_shell_argument(&format!("./{path}"), cfg!(windows))
            ),
            generated_command: Some(format!(
                "{interpreter} {}",
                quote_shell_argument(&format!("./{path}"), cfg!(windows))
            )),
            view: BottomView::Run,
            working_directory: Some(source_root.to_owned()),
        })
        .collect()
}

fn quote_shell_argument(argument: &str, windows: bool) -> String {
    if windows {
        format!("'{}'", argument.replace('\'', "''"))
    } else {
        format!("'{}'", argument.replace('\'', "'\"'\"'"))
    }
}

fn read_configs(path: &Path) -> Result<Option<Vec<RunConfig>>, String> {
    let data = match fs::read(path) {
        Ok(data) => data,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error.to_string()),
    };
    if data.len() > 1024 * 1024 {
        return Err("fichier de configurations trop volumineux".into());
    }
    let file: ConfigFile = serde_json::from_slice(&data).map_err(|error| error.to_string())?;
    if file.version != 1 {
        return Err(format!("version {} non prise en charge", file.version));
    }
    Ok(Some(file.configurations))
}

fn write_configs(path: &Path, configurations: &[RunConfig]) -> Result<(), String> {
    let directory = path.parent().ok_or("Dossier de configurations absent")?;
    fs::create_dir_all(directory).map_err(|error| error.to_string())?;
    let file = ConfigFile {
        version: 1,
        configurations: configurations.to_vec(),
    };
    let mut temporary =
        tempfile::NamedTempFile::new_in(directory).map_err(|error| error.to_string())?;
    serde_json::to_writer_pretty(&mut temporary, &file).map_err(|error| error.to_string())?;
    temporary
        .write_all(b"\n")
        .map_err(|error| error.to_string())?;
    temporary
        .as_file()
        .sync_all()
        .map_err(|error| error.to_string())?;
    temporary.persist(path).map_err(|error| error.to_string())?;
    Ok(())
}

enum Control {
    Input(String),
    CloseInput,
    Stop,
}

enum ProcessEvent {
    Started(u32),
    Output(String),
    Finished { code: Option<i32>, stopped: bool },
    Error(String),
}

struct RunSession {
    id: u64,
    name: String,
    command: String,
    view: BottomView,
    worktree_id: String,
    root: PathBuf,
    output: String,
    truncated: bool,
    stdin: String,
    started: Instant,
    elapsed: Option<Duration>,
    pid: Option<u32>,
    result: Option<(Option<i32>, bool)>,
    failed_to_start: bool,
    stopping: bool,
    control: Sender<Control>,
    events: Option<Receiver<ProcessEvent>>,
    worker: Option<JoinHandle<()>>,
}

impl RunSession {
    fn start(
        id: u64,
        name: String,
        command: String,
        view: BottomView,
        worktree_id: String,
        root: PathBuf,
    ) -> Self {
        let (control, controls) = mpsc::channel();
        let (events_sender, events) = mpsc::sync_channel(64);
        let worker_command = command.clone();
        let worker_root = root.clone();
        let worker = thread::spawn(move || {
            run_process(&worker_command, &worker_root, controls, events_sender)
        });
        Self {
            id,
            name,
            command: command.clone(),
            view,
            worktree_id,
            root,
            output: format!("$ {command}\n"),
            truncated: false,
            stdin: String::new(),
            started: Instant::now(),
            elapsed: None,
            pid: None,
            result: None,
            failed_to_start: false,
            stopping: false,
            control,
            events: Some(events),
            worker: Some(worker),
        }
    }

    fn is_running(&self) -> bool {
        self.result.is_none() && !self.failed_to_start
    }

    fn poll(&mut self) -> bool {
        let mut changed = false;
        for _ in 0..128 {
            let event = match self.events.as_ref().map(Receiver::try_recv) {
                Some(Ok(event)) => event,
                Some(Err(mpsc::TryRecvError::Disconnected)) if self.is_running() => {
                    self.failed_to_start = true;
                    self.elapsed = Some(self.started.elapsed());
                    self.append_output("\nLe canal de la commande a été fermé.\n");
                    changed = true;
                    break;
                }
                _ => break,
            };
            changed = true;
            match event {
                ProcessEvent::Started(pid) => self.pid = Some(pid),
                ProcessEvent::Output(text) => self.append_output(&text),
                ProcessEvent::Finished { code, stopped } => {
                    self.result = Some((code, stopped));
                    self.elapsed = Some(self.started.elapsed());
                }
                ProcessEvent::Error(message) => {
                    self.append_output(&format!("\n{message}\n"));
                    if self.pid.is_none() {
                        self.failed_to_start = true;
                        self.elapsed = Some(self.started.elapsed());
                    }
                }
            }
        }
        changed
    }

    fn append_output(&mut self, text: &str) {
        self.output.push_str(text);
        if self.output.len() > OUTPUT_LIMIT {
            let mut keep_from = self.output.len() - OUTPUT_LIMIT;
            while !self.output.is_char_boundary(keep_from) {
                keep_from += 1;
            }
            self.output.drain(..keep_from);
            self.truncated = true;
        }
    }

    fn stop(&mut self) {
        if self.is_running() {
            let _ = self.control.send(Control::Stop);
            self.stopping = true;
        }
    }

    fn status_symbol(&self) -> &'static str {
        match self.result {
            Some((_, true)) => "■",
            Some((Some(0), false)) => "✓",
            Some(_) => "×",
            None if self.failed_to_start => "!",
            None => "●",
        }
    }

    fn status_text(&self) -> String {
        let seconds = self
            .elapsed
            .unwrap_or_else(|| self.started.elapsed())
            .as_secs_f32();
        let status = match self.result {
            Some((_, true)) => "Arrêté".to_owned(),
            Some((Some(0), false)) if self.view == BottomView::Tests => {
                "Commande de test réussie · code 0".to_owned()
            }
            Some((Some(0), false)) => "Terminé · code 0".to_owned(),
            Some((Some(code), false)) => format!("Échec · code {code}"),
            Some((None, false)) => "Terminé par un signal".to_owned(),
            None if self.failed_to_start => "Lancement impossible".to_owned(),
            None if self.stopping => "Arrêt en cours…".to_owned(),
            None => "En cours".to_owned(),
        };
        format!("{status} · {seconds:.1} s")
    }
}

impl Drop for RunSession {
    fn drop(&mut self) {
        let _ = self.control.send(Control::Stop);
        // Unblock readers before waiting for shutdown, even with a full output queue.
        self.events.take();
        if let Some(worker) = self.worker.take() {
            let _ = worker.join();
        }
    }
}

fn shell_command(command: &str, root: &Path) -> Command {
    #[cfg(windows)]
    let mut process = {
        use std::os::windows::process::CommandExt;
        let mut process = Command::new("powershell.exe");
        process.args(["-NoLogo", "-NoProfile", "-NonInteractive", "-Command"]);
        // Native commands propagate their exit status. PowerShell errors set $? false.
        process.arg(format!("[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false); $OutputEncoding = [Console]::OutputEncoding; $global:LASTEXITCODE = 0; & {{\n{command}\n}}; if (-not $?) {{ if ($LASTEXITCODE -ne 0) {{ exit $LASTEXITCODE }}; exit 1 }}; exit $LASTEXITCODE"));
        process.creation_flags(0x0800_0000); // CREATE_NO_WINDOW
        process
    };
    #[cfg(unix)]
    let mut process = {
        use std::os::unix::process::CommandExt;
        let mut process = Command::new("/bin/sh");
        process.args(["-c", command]);
        process.process_group(0);
        process
    };
    process
        .current_dir(root)
        .env("PYTHONUNBUFFERED", "1")
        .env("PYTHONIOENCODING", "utf-8")
        .env("NO_COLOR", "1")
        .env("TERM", "dumb")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    process
}

fn run_process(
    command: &str,
    root: &Path,
    controls: Receiver<Control>,
    events: SyncSender<ProcessEvent>,
) {
    let mut child = match shell_command(command, root).spawn() {
        Ok(child) => child,
        Err(error) => {
            let _ = events.send(ProcessEvent::Error(format!(
                "Impossible de lancer la commande : {error}"
            )));
            return;
        }
    };
    let _ = events.send(ProcessEvent::Started(child.id()));
    let mut input = child.stdin.take().map(|mut stdin| {
        let (sender, receiver) = mpsc::sync_channel::<String>(16);
        let events = events.clone();
        // A program that does not read stdin must not block the supervisor's Stop action.
        thread::spawn(move || {
            while let Ok(text) = receiver.recv() {
                if let Err(error) = stdin
                    .write_all(text.as_bytes())
                    .and_then(|()| stdin.flush())
                {
                    let _ = events.send(ProcessEvent::Error(format!("Entrée standard : {error}")));
                    break;
                }
            }
        });
        sender
    });
    let (reader_done, readers_done) = mpsc::channel();
    for pipe in [
        child
            .stdout
            .take()
            .map(|pipe| Box::new(pipe) as Box<dyn Read + Send>),
        child
            .stderr
            .take()
            .map(|pipe| Box::new(pipe) as Box<dyn Read + Send>),
    ]
    .into_iter()
    .flatten()
    {
        let sender = events.clone();
        let done = reader_done.clone();
        thread::spawn(move || {
            stream_output(pipe, sender);
            let _ = done.send(());
        });
    }
    drop(reader_done);
    let mut stopped = false;
    let result = loop {
        match controls.recv_timeout(Duration::from_millis(40)) {
            Ok(Control::Input(text)) => {
                if text.len() > 64 * 1024 {
                    let _ = events.send(ProcessEvent::Error(
                        "L’entrée dépasse 64 Kio ; envoyez-la en plusieurs lignes.".into(),
                    ));
                } else if let Some(stdin) = &input {
                    match stdin.try_send(text) {
                        Ok(()) => {}
                        Err(mpsc::TrySendError::Full(_)) => {
                            let _ = events.send(ProcessEvent::Error("Le programme ne lit pas assez vite son entrée ; cette ligne n’a pas été envoyée.".into()));
                        }
                        Err(mpsc::TrySendError::Disconnected(_)) => {
                            input = None;
                            let _ = events
                                .send(ProcessEvent::Error("L’entrée standard est fermée.".into()));
                        }
                    }
                }
            }
            Ok(Control::CloseInput) => input = None,
            Ok(Control::Stop) | Err(mpsc::RecvTimeoutError::Disconnected) => {
                stopped = true;
                input = None;
                terminate_tree(&mut child);
            }
            Err(mpsc::RecvTimeoutError::Timeout) => {}
        }
        match child.try_wait() {
            Ok(Some(status)) => break Some(status),
            Ok(None) => {}
            Err(error) => {
                let _ = events.send(ProcessEvent::Error(format!("Suivi du processus : {error}")));
                terminate_tree(&mut child);
                break child.wait().ok();
            }
        }
    };
    drop(input);
    // Normal children close both pipes; background descendants must not hold the UI forever.
    let deadline = Instant::now() + Duration::from_millis(600);
    while let Some(remaining) = deadline.checked_duration_since(Instant::now()) {
        match readers_done.recv_timeout(remaining) {
            Ok(()) => {}
            Err(_) => break,
        }
    }
    let _ = events.send(ProcessEvent::Finished {
        code: result.and_then(|status| status.code()),
        stopped,
    });
}

fn terminate_tree(child: &mut Child) {
    if !matches!(child.try_wait(), Ok(None)) {
        return;
    }
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        let _ = Command::new("taskkill.exe")
            .args(["/PID", &child.id().to_string(), "/T", "/F"])
            .creation_flags(0x0800_0000)
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
    #[cfg(unix)]
    {
        // shell_command created this process group, so no unrelated shell is signalled.
        let group = -(child.id() as i32);
        unsafe {
            libc::kill(group, libc::SIGKILL);
        }
    }
    let _ = child.kill();
}

fn stream_output(mut reader: impl Read, events: SyncSender<ProcessEvent>) {
    let mut buffer = [0_u8; 4096];
    let mut decoder = OutputDecoder::default();
    loop {
        match reader.read(&mut buffer) {
            Ok(0) => break,
            Ok(length) => {
                let output = decoder.push(&buffer[..length], false);
                if !output.is_empty() && events.send(ProcessEvent::Output(output)).is_err() {
                    return;
                }
            }
            Err(error) if error.kind() == std::io::ErrorKind::Interrupted => continue,
            Err(error) => {
                let _ = events.send(ProcessEvent::Error(format!(
                    "Lecture de la sortie : {error}"
                )));
                break;
            }
        }
    }
    let output = decoder.push(&[], true);
    if !output.is_empty() {
        let _ = events.send(ProcessEvent::Output(output));
    }
}

/// Preserves UTF-8 split across reads and removes ANSI controls across chunk boundaries.
#[derive(Default)]
struct OutputDecoder {
    pending: Vec<u8>,
    escape: u8,
}

impl OutputDecoder {
    fn push(&mut self, bytes: &[u8], finish: bool) -> String {
        self.pending.extend_from_slice(bytes);
        let mut text = String::new();
        loop {
            match std::str::from_utf8(&self.pending) {
                Ok(valid) => {
                    text.push_str(valid);
                    self.pending.clear();
                    break;
                }
                Err(error) => {
                    let valid = error.valid_up_to();
                    text.push_str(
                        std::str::from_utf8(&self.pending[..valid]).expect("UTF-8 prefix checked"),
                    );
                    self.pending.drain(..valid);
                    if let Some(invalid) = error.error_len() {
                        text.push('\u{fffd}');
                        self.pending.drain(..invalid);
                    } else {
                        if finish {
                            text.push_str(&String::from_utf8_lossy(&self.pending));
                            self.pending.clear();
                        }
                        break;
                    }
                }
            }
        }
        let mut output = String::new();
        for ch in text.chars() {
            match self.escape {
                0 if ch == '\u{1b}' => self.escape = 1,
                0 if !ch.is_control() || ch == '\n' || ch == '\t' => output.push(ch),
                1 if ch == '[' => self.escape = 2,
                1 if ch == ']' => self.escape = 3,
                1 => self.escape = 0,
                2 if ('@'..='~').contains(&ch) => self.escape = 0,
                3 if ch == '\u{7}' => self.escape = 0,
                3 if ch == '\u{1b}' => self.escape = 4,
                4 if ch == '\\' => self.escape = 0,
                4 => self.escape = 3,
                _ => {}
            }
        }
        output
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn collect_session(session: &mut RunSession, timeout: Duration) {
        let deadline = Instant::now() + timeout;
        while session.is_running() && Instant::now() < deadline {
            session.poll();
            thread::sleep(Duration::from_millis(15));
        }
        session.poll();
        assert!(
            !session.is_running(),
            "command did not finish: {}",
            session.output
        );
    }

    #[test]
    fn configurations_roundtrip_without_running_commands() {
        let project = tempfile::tempdir().unwrap();
        let mut panel = RunPanel::new(project.path().into());
        assert!(!project.path().join(".pie_crust").exists());
        panel.selected_config = panel.configurations.len();
        panel.edit_name = "Commande avec espaces".into();
        panel.edit_command = "echo 'édition ✓'".into();
        panel.edit_view = BottomView::Tests;
        panel.save_edited();
        assert!(panel.error.is_none());
        assert!(!panel.is_running());
        panel.edit_command = "echo 'mise à jour'".into();
        panel.save_edited();
        let reopened = RunPanel::new(project.path().into());
        let saved = reopened.configurations.last().unwrap();
        assert_eq!(saved.name, "Commande avec espaces");
        assert_eq!(saved.command, "echo 'mise à jour'");
        assert_eq!(saved.view, BottomView::Tests);
    }

    #[test]
    fn script_discovery_quotes_paths_and_refresh_preserves_custom_commands_without_execution() {
        let project = tempfile::tempdir().unwrap();
        fs::create_dir_all(project.path().join("scripts/deeper")).unwrap();
        fs::write(
            project.path().join("O'Brien $value.py"),
            "raise RuntimeError('never execute discovery')",
        )
        .unwrap();
        fs::write(
            project.path().join("scripts/send mail.py"),
            "raise RuntimeError('never execute discovery')",
        )
        .unwrap();
        fs::write(project.path().join("scripts/deeper/hidden.py"), "pass").unwrap();
        fs::write(project.path().join("test_app.py"), "pass").unwrap();
        fs::write(project.path().join("manage.py"), "pass").unwrap();
        let mut panel = RunPanel::new(project.path().into());
        let scripts: Vec<_> = panel
            .configurations
            .iter()
            .filter(|configuration| configuration.name.starts_with("Python · "))
            .collect();
        assert_eq!(scripts.len(), 2);
        assert!(scripts.iter().any(|configuration| {
            configuration
                .command
                .ends_with(&quote_shell_argument("./O'Brien $value.py", cfg!(windows)))
        }));
        assert!(
            scripts
                .iter()
                .any(|configuration| configuration.name == "Python · scripts/send mail.py")
        );
        assert_eq!(quote_shell_argument("a'b $c.py", true), "'a''b $c.py'");
        assert_eq!(
            quote_shell_argument("a'b $c.py", false),
            "'a'\"'\"'b $c.py'"
        );
        assert!(!panel.is_running());
        assert!(!project.path().join(".pie_crust").exists());

        let index = panel
            .configurations
            .iter()
            .position(|configuration| configuration.name == "Python · scripts/send mail.py")
            .unwrap();
        panel.configurations[index].command = "python custom_entry.py --user-flag".into();
        fs::write(project.path().join("scripts/new.py"), "pass").unwrap();
        panel.refresh_scripts();
        panel.refresh_scripts();
        assert_eq!(
            panel.configurations[index].command,
            "python custom_entry.py --user-flag"
        );
        assert_eq!(
            panel
                .configurations
                .iter()
                .filter(|configuration| configuration.name == "Python · scripts/new.py")
                .count(),
            1
        );
        assert!(!panel.is_running());
    }

    #[test]
    fn discovery_is_bounded_and_interpreter_uses_the_selected_root() {
        let project = tempfile::tempdir().unwrap();
        for index in 0..70 {
            fs::write(project.path().join(format!("script_{index:02}.py")), "pass").unwrap();
        }
        assert_eq!(discover_scripts(project.path(), Path::new(".")).len(), 64);
        let other = tempfile::tempdir().unwrap();
        let environment = if cfg!(windows) {
            ".venv/Scripts/python.exe"
        } else {
            ".venv/bin/python"
        };
        let interpreter = other.path().join(environment);
        fs::create_dir_all(interpreter.parent().unwrap()).unwrap();
        fs::write(&interpreter, "").unwrap();
        assert!(python_interpreter_in_source_root(other.path(), Path::new(".")).contains(".venv"));
        assert!(
            !python_interpreter_in_source_root(project.path(), Path::new(".")).contains(".venv")
        );
    }

    fn nested_python_project(root: &Path) -> PathBuf {
        let source_root = PathBuf::from("back-end/frigo-recettes");
        fs::create_dir_all(root.join(&source_root).join("scripts")).unwrap();
        fs::write(
            root.join(&source_root).join("pyproject.toml"),
            "[project]\nname = 'frigo-recettes'\nversion = '0.1.0'\n",
        )
        .unwrap();
        fs::write(
            root.join(&source_root).join("manage.py"),
            "raise RuntimeError('discovery must not execute')",
        )
        .unwrap();
        fs::write(
            root.join(&source_root).join("scripts/seed data.py"),
            "raise RuntimeError('discovery must not execute')",
        )
        .unwrap();
        source_root
    }

    fn create_environment(root: &Path, name: &str) -> PathBuf {
        let environment = root.join(name);
        let interpreter = environment.join(if cfg!(windows) {
            "Scripts/python.exe"
        } else {
            "bin/python"
        });
        fs::create_dir_all(interpreter.parent().unwrap()).unwrap();
        fs::write(environment.join("pyvenv.cfg"), "home = python\n").unwrap();
        fs::write(&interpreter, "").unwrap();
        interpreter
    }

    #[test]
    fn nested_defaults_and_scripts_capture_source_cwd_without_retargeting_worktree() {
        let project = tempfile::tempdir().unwrap();
        let source_root = nested_python_project(project.path());
        create_environment(&project.path().join(&source_root), ".venv");
        let mut panel = RunPanel::new(project.path().into());
        panel.set_worktree("main", project.path().into());
        assert_eq!(panel.primary_source_root, source_root);
        let django = panel
            .configurations
            .iter()
            .position(|configuration| configuration.name == "Django · serveur")
            .unwrap();
        assert_eq!(
            panel.configurations[django].working_directory.as_deref(),
            Some(source_root.as_path())
        );
        assert!(panel.configurations[django].command.contains("./.venv/"));
        panel.selected_config = django;
        panel.run_selected();
        let request = panel.take_run_request().unwrap();
        assert_eq!(request.root, project.path());
        assert_eq!(request.worktree_id, "main");
        assert!(request.command.contains("'./back-end/frigo-recettes'"));
        assert!(request.command.ends_with("manage.py runserver"));
        let script = panel
            .configurations
            .iter()
            .find(|configuration| {
                configuration.name == "Python · back-end/frigo-recettes/scripts/seed data.py"
            })
            .unwrap();
        assert_eq!(
            script.working_directory.as_deref(),
            Some(source_root.as_path())
        );
        assert!(script.command.ends_with("'./scripts/seed data.py'"));
        assert!(!panel.is_running());
        assert!(!project.path().join(".pie_crust").exists());
    }

    #[test]
    fn python_commands_use_selected_source_root_and_nearest_environment() {
        let project = tempfile::tempdir().unwrap();
        let source_root = nested_python_project(project.path());
        create_environment(project.path(), "shared environment");
        let mut panel = RunPanel::new(project.path().into());
        panel.run_python_command_in_source_root(
            "Packages",
            "-m pip list",
            BottomView::Run,
            &source_root,
        );
        let request = panel.take_run_request().unwrap();
        assert!(
            request.command.contains("'./../../shared environment/"),
            "{}",
            request.command
        );
        assert!(request.command.contains("'./back-end/frigo-recettes'"));
        if cfg!(windows) {
            assert!(request.command.contains("; & '"));
        }
        create_environment(&project.path().join(&source_root), "venv");
        panel.run_python_command_in_source_root(
            "Packages",
            "-m pip list",
            BottomView::Run,
            &source_root,
        );
        let request = panel.take_run_request().unwrap();
        assert!(request.command.contains("'./venv/"));
        assert!(!request.command.contains("shared environment"));
        assert_eq!(request.root, project.path());
    }

    #[test]
    fn python_command_reports_rejected_launch_without_a_pending_request() {
        let project = tempfile::tempdir().unwrap();
        let mut panel = RunPanel::new(project.path().into());
        assert!(!panel.run_python_command_in_source_root(
            "Missing source",
            "-m pip list",
            BottomView::Run,
            Path::new("missing"),
        ));
        assert!(panel.take_run_request().is_none());
        for _ in 0..8 {
            assert!(panel.run_python_command_in_source_root(
                "Pending command",
                "-m pip list",
                BottomView::Run,
                Path::new("."),
            ));
        }
        assert!(!panel.run_python_command_in_source_root(
            "Queue full",
            "-m pip list",
            BottomView::Run,
            Path::new("."),
        ));
        assert_eq!(panel.run_requests.len(), 8);
        assert!(!panel.is_running());
    }

    #[test]
    fn legacy_and_custom_configurations_keep_worktree_cwd_and_project_persistence() {
        let project = tempfile::tempdir().unwrap();
        nested_python_project(project.path());
        let path = project.path().join(".pie_crust/run-configs.json");
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(
            &path,
            r#"{"version":1,"configurations":[{"name":"Custom","command":"echo custom"}]}"#,
        )
        .unwrap();
        let mut panel = RunPanel::new(project.path().into());
        panel.run_selected();
        let request = panel.take_run_request().unwrap();
        assert_eq!(request.command, "echo custom");
        assert_eq!(request.root, project.path());
        panel.edit_command = "echo changed".into();
        panel.save_edited();
        let reopened = RunPanel::new(project.path().into());
        assert_eq!(reopened.configurations[0].command, "echo changed");
        assert_eq!(reopened.configurations[0].working_directory, None);
        assert!(
            !project
                .path()
                .join("back-end/frigo-recettes/.pie_crust")
                .exists()
        );
        assert!(
            command_in_directory(project.path(), Some(Path::new("../outside")), "echo custom")
                .is_err()
        );
    }

    #[test]
    fn generated_configurations_follow_worktree_layout_and_environment_without_changing_custom_commands()
     {
        let project = tempfile::tempdir().unwrap();
        let source_root = nested_python_project(project.path());
        create_environment(&project.path().join(&source_root), ".venv");
        let mut panel = RunPanel::new(project.path().into());
        let pytest = panel
            .configurations
            .iter()
            .position(|configuration| configuration.name == "Tests · pytest")
            .unwrap();
        panel.selected_config = pytest;
        panel.load_selected();
        panel.edit_command = "python -m pytest --custom".into();
        panel.save_edited();
        assert!(panel.configurations[pytest].generated_command.is_none());

        let other = tempfile::tempdir().unwrap();
        fs::write(
            other.path().join("pyproject.toml"),
            "[project]\nname = 'root-project'\nversion = '0.1.0'\n",
        )
        .unwrap();
        fs::write(other.path().join("manage.py"), "pass").unwrap();
        create_environment(other.path(), "active environment");
        panel.set_worktree("other", other.path().into());
        let django = panel
            .configurations
            .iter()
            .find(|configuration| configuration.name == "Django · serveur")
            .unwrap();
        assert_eq!(django.working_directory.as_deref(), Some(Path::new(".")));
        assert!(django.command.contains("'./active environment/"));
        let pytest = panel
            .configurations
            .iter()
            .find(|configuration| configuration.name == "Tests · pytest")
            .unwrap();
        assert_eq!(pytest.command, "python -m pytest --custom");
        assert_eq!(
            pytest.working_directory.as_deref(),
            Some(source_root.as_path())
        );
        assert_eq!(
            panel.config_path,
            project.path().join(".pie_crust/run-configs.json")
        );
        assert!(
            !panel
                .configurations
                .iter()
                .any(|configuration| configuration.name
                    == "Python · back-end/frigo-recettes/scripts/seed data.py")
        );
    }

    #[test]
    fn source_command_executes_quoted_environment_in_source_cwd_and_preserves_exit_status() {
        let project = tempfile::tempdir().unwrap();
        let source_root = Path::new("back-end/chef's recipes");
        fs::create_dir_all(project.path().join(source_root)).unwrap();
        fs::write(
            project.path().join(source_root).join("marker.txt"),
            "source-cwd-correct",
        )
        .unwrap();
        let interpreter = create_environment(project.path(), "user's environment");
        // The test harness is a portable native executable: no project or Python code runs.
        fs::copy(std::env::current_exe().unwrap(), &interpreter).unwrap();
        let mut panel = RunPanel::new(project.path().into());
        let args = if cfg!(windows) {
            "--list; if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }; Get-Content -LiteralPath marker.txt; exit 7"
        } else {
            "--list && cat marker.txt; exit 7"
        };
        panel.run_python_command_in_source_root(
            "Environment test",
            args,
            BottomView::Run,
            source_root,
        );
        let request = panel.take_run_request().unwrap();
        assert_eq!(request.root, project.path());
        assert!(panel.start_request(request));
        let session = panel.sessions.last_mut().unwrap();
        collect_session(session, Duration::from_secs(20));
        assert_eq!(session.result, Some((Some(7), false)), "{}", session.output);
        assert!(session.output.contains("source_command_executes_quoted_environment_in_source_cwd_and_preserves_exit_status: test"), "{}", session.output);
        assert!(
            session.output.contains("source-cwd-correct"),
            "{}",
            session.output
        );
    }

    #[test]
    fn malformed_saved_configurations_are_reported_without_overwriting_them() {
        let project = tempfile::tempdir().unwrap();
        let configuration = project.path().join(".pie_crust/run-configs.json");
        fs::create_dir_all(configuration.parent().unwrap()).unwrap();
        fs::write(&configuration, "{ broken json").unwrap();
        let panel = RunPanel::new(project.path().into());
        assert!(panel.error.is_some());
        assert_eq!(fs::read_to_string(configuration).unwrap(), "{ broken json");
        assert!(!panel.is_running());
    }

    #[test]
    fn output_preserves_split_unicode_and_strips_split_ansi_sequences() {
        let mut decoder = OutputDecoder::default();
        assert_eq!(decoder.push(b"caf\xc3", false), "caf");
        assert_eq!(decoder.push(b"\xa9\x1b[3", false), "é");
        assert_eq!(decoder.push(b"1m error\x1b[0m\r\n", false), " error\n");
        assert_eq!(decoder.push(b"\x1b]0;title", false), "");
        assert_eq!(decoder.push(b"\x1b\\done", true), "done");
    }

    #[test]
    fn command_reports_worktree_stdout_stderr_and_exit_status() {
        let project = tempfile::tempdir().unwrap();
        fs::write(project.path().join("marker.txt"), "worktree-correct").unwrap();
        let command = if cfg!(windows) {
            "Get-Content marker.txt; [Console]::Error.WriteLine('stderr-marker'); exit 7"
        } else {
            "cat marker.txt; printf 'stderr-marker\\n' >&2; exit 7"
        };
        let mut session = RunSession::start(
            1,
            "test".into(),
            command.into(),
            BottomView::Run,
            "worktree-a".into(),
            project.path().into(),
        );
        collect_session(&mut session, Duration::from_secs(20));
        assert_eq!(session.result, Some((Some(7), false)));
        assert!(session.output.contains("worktree-correct"));
        assert!(session.output.contains("stderr-marker"));
    }

    #[test]
    fn standard_input_and_stop_are_real_process_operations() {
        let project = tempfile::tempdir().unwrap();
        let command = if cfg!(windows) {
            "$line = [Console]::ReadLine(); [Console]::WriteLine('received:' + $line); Start-Sleep -Seconds 60"
        } else {
            "read line; printf 'received:%s\\n' \"$line\"; sleep 60"
        };
        let mut session = RunSession::start(
            1,
            "input".into(),
            command.into(),
            BottomView::Terminal,
            "worktree-a".into(),
            project.path().into(),
        );
        session
            .control
            .send(Control::Input("hello-input\n".into()))
            .unwrap();
        let deadline = Instant::now() + Duration::from_secs(20);
        while !session.output.contains("received:hello-input") && Instant::now() < deadline {
            session.poll();
            thread::sleep(Duration::from_millis(15));
        }
        assert!(
            session.output.contains("received:hello-input"),
            "{}",
            session.output
        );
        session.stop();
        collect_session(&mut session, Duration::from_secs(10));
        assert!(session.result.is_some_and(|(_, stopped)| stopped));
    }

    #[test]
    fn switching_worktree_does_not_retarget_a_running_command() {
        let project = tempfile::tempdir().unwrap();
        let other = tempfile::tempdir().unwrap();
        let mut panel = RunPanel::new(project.path().into());
        panel.set_worktree("first", project.path().into());
        panel.run_command("echo", "echo first-root", BottomView::Run);
        assert!(!panel.is_running());
        assert!(panel.sessions.is_empty());
        let request = panel.take_run_request().unwrap();
        assert_eq!(request.worktree_id, "first");
        assert_eq!(request.root, project.path());
        let root = other.path().to_path_buf();
        let prepared = thread::spawn(move || {
            let mut prepared = RunPanel::new(root.clone());
            prepared.set_worktree("second", root);
            prepared
        })
        .join()
        .unwrap();
        panel.adopt_project(prepared);
        assert!(panel.start_request(request));
        let session = panel.sessions.last_mut().unwrap();
        assert_eq!(session.worktree_id, "first");
        assert_eq!(session.root, project.path());
        collect_session(session, Duration::from_secs(20));
        assert_eq!(session.result, Some((Some(0), false)));
    }

    #[test]
    fn prepared_worktree_keeps_in_memory_configuration_and_unsaved_edits() {
        let project = tempfile::tempdir().unwrap();
        let other = tempfile::tempdir().unwrap();
        let mut panel = RunPanel::new(project.path().into());
        panel.set_worktree("first", project.path().into());
        panel.configurations[0].name = "Custom in memory".into();
        panel.configurations[0].command = "python -m pytest --custom".into();
        panel.configurations[0].generated_command = None;
        panel.load_selected();
        panel.edit_name = "Unsaved configuration name".into();
        panel.edit_command = "python -m pytest --unsaved-draft".into();
        panel.edit_view = BottomView::Run;
        panel.terminal_command = "echo terminal draft".into();

        let prepare = panel.prepare_worktree("second".into(), other.path().into());
        // Discovery must happen on the worker, after the snapshot has been captured.
        fs::write(other.path().join("new_script.py"), "pass").unwrap();
        let prepared = thread::spawn(prepare).join().unwrap();
        assert_eq!(panel.worktree_id, "first");
        panel.adopt_project(prepared);

        assert_eq!(panel.worktree_id, "second");
        assert_eq!(panel.worktree_root, other.path());
        assert_eq!(
            panel.config_path,
            project.path().join(".pie_crust/run-configs.json")
        );
        assert_eq!(panel.configurations[0].name, "Custom in memory");
        assert_eq!(panel.configurations[0].command, "python -m pytest --custom");
        assert_eq!(panel.edit_name, "Unsaved configuration name");
        assert_eq!(panel.edit_command, "python -m pytest --unsaved-draft");
        assert_eq!(panel.edit_view, BottomView::Run);
        assert_eq!(panel.terminal_command, "echo terminal draft");
        assert!(
            panel
                .configurations
                .iter()
                .any(|configuration| { configuration.name == "Python · new_script.py" })
        );
        assert!(!project.path().join(".pie_crust").exists());
        assert!(!other.path().join(".pie_crust").exists());
    }

    #[test]
    fn adopting_prepared_project_keeps_sessions_terminals_and_pending_requests() {
        let project = tempfile::tempdir().unwrap();
        let other = tempfile::tempdir().unwrap();
        let mut panel = RunPanel::new(project.path().into());
        panel.set_worktree("first", project.path().into());
        panel.run_command("original run", "echo first-root", BottomView::Tests);
        let request = panel.take_run_request().unwrap();
        assert!(panel.start_request(request));
        let terminal_request = RunRequest {
            name: "original terminal".into(),
            command: "echo terminal-root".into(),
            view: BottomView::Terminal,
            worktree_id: "first".into(),
            root: project.path().into(),
            terminal_id: None,
        };
        assert!(panel.start_request(terminal_request.clone()));
        panel.run_command("pending", "echo pending-root", BottomView::Run);
        panel.open_run_popup();
        panel.terminal_command = "old project draft".into();
        let root = other.path().to_path_buf();
        let prepared = thread::spawn(move || {
            let mut prepared = RunPanel::new(root.clone());
            prepared.set_worktree("second", root);
            prepared
        })
        .join()
        .unwrap();
        let requested_view = panel.requested_view;
        let terminal_requested_view = panel.terminals.requested_view;
        panel.adopt_project(prepared);

        assert_eq!(panel.worktree_id, "second");
        assert_eq!(panel.worktree_root, other.path());
        assert_eq!(
            panel.config_path,
            other.path().join(".pie_crust/run-configs.json")
        );
        assert!(panel.terminal_command.is_empty());
        assert!(panel.popup_open);
        assert!(panel.focus_command);
        assert_eq!(panel.sessions.len(), 1);
        assert_eq!(panel.selected_session, Some(1));
        assert_eq!(panel.next_session, 2);
        assert_eq!(panel.terminals.requested_view, terminal_requested_view);
        assert_eq!(panel.requested_view, requested_view);
        let pending = panel.take_run_request().unwrap();
        assert_eq!(pending.name, "pending");
        assert_eq!(pending.worktree_id, "first");
        assert_eq!(pending.root, project.path());
        let session = &mut panel.sessions[0];
        assert_eq!(session.worktree_id, "first");
        assert_eq!(session.root, project.path());
        collect_session(session, Duration::from_secs(20));
        assert!(session.output.contains("first-root"));

        let deadline = Instant::now() + Duration::from_secs(20);
        while panel.terminals.is_running() && Instant::now() < deadline {
            panel.poll();
            thread::sleep(Duration::from_millis(15));
        }
        assert!(!panel.terminals.is_running());
        // Reusing its original id and context proves the existing shell survived.
        assert!(panel.start_request(RunRequest {
            terminal_id: Some(1),
            ..terminal_request
        }));
    }

    #[test]
    fn rejected_launch_request_never_starts_a_process() {
        let project = tempfile::tempdir().unwrap();
        let mut panel = RunPanel::new(project.path().into());
        panel.set_worktree("first", project.path().into());
        panel.run_command(
            "must stay pending",
            "echo unexpected > unexpected.txt",
            BottomView::Run,
        );
        let request = panel.take_run_request().unwrap();
        assert_eq!(request.name, "must stay pending");
        assert!(panel.take_run_request().is_none());
        panel.set_launch_error("Un document n’a pas pu être sauvegardé.");
        assert!(!panel.is_running());
        assert!(panel.sessions.is_empty());
        assert!(!project.path().join("unexpected.txt").exists());
        assert_eq!(
            panel.error.as_deref(),
            Some("Un document n’a pas pu être sauvegardé.")
        );
    }
}
